Integrate SVG Pieces with Vue Application
walshb421/chess pull request #26
Opened 2024-03-02 00:58 UTC by Bryonnab

closes #16

2024-03-02 22:38 UTC, walshb421 commented on engine/app.py
> +        await websocket.send(board.game_to_json())
@GarettOS I had to comment out the move validation to get this PR to work, but its pretty cool to be able to move all of the pieces around right now

2024-03-02 22:43 UTC, walshb421 requested changes
You should delete the separate svg files that are not needed here

2024-03-03 00:44 UTC, walshb421 approved these changes

2024-03-07 00:49 UTC, GarettOS reviewed
super duper!

2024-03-07 00:55 UTC, walshb421 approved these changes

2024-03-07 00:55 UTC, GarettOS approved these changes

2024-03-07 01:03 UTC, merged