Add simple board and python class
walshb421/chess pull request #7
Opened 2024-02-29 04:58 UTC by GarettOS

closes #8

2024-02-29 08:59 UTC, GarettOS commented
> [Feb 28, 2024](#event-11960680749)
done

2024-02-29 09:02 UTC, GarettOS commented
> I don't see this integrated with the websocket

done

2024-03-01 05:27 UTC, walshb421 requested changes
This looks awesome! I was able to move a pawn, got it to crash somehow but that is to be expected at this point! Excited to get this merged so that I can get working on adapting my board to it. If you delete those files and push, it I will be satisfied!

2024-03-01 05:27 UTC, walshb421 commented on engine/__pycache__/board.cpython-38.pyc
You should delete this directory from your commit:
```bash
git rm -rf ./engine/__pycache__/
git commit -m "Removed Python Cache files"
```

2024-03-01 19:19 UTC, walshb421 approved these changes

2024-03-01 19:25 UTC, merged